# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  major: 1
  minor: 0

name: $(major).$(minor).$(Rev:.r)

steps:
- script: |
    dotnet publish ./src/PrintSpooler/ --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY/PrintSpooler.win64 --self-contained true -r win-x64
  failOnStderr: true
  displayName: Build PrintSpooler Win x64
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/PrintSpooler.win64'
    artifactName: 'PrintSpooler.win64'
  displayName: Publish PrintSpooler Win x64 artifacts