# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'
  Version.MajorMinor: 1.0
  Version.Patch: $[counter(variables['Version.MajorMinor'], 0)]

name: $(Version.MajorMinor).$(Version.Patch)

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/PrintSpooler'
    versioningScheme: byBuildNumber
    zipAfterPublish: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/PrintSpooler-win64'
- publish: PrintSpooler-win64
  artifact: PrintSpooler-win64