trigger:
  branches:
    include:
    - master
    - releases/*
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GithubRelease@0
  displayName: 'Attach artifact assets to GitHub Release'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  inputs:
    gitHubConnection: github
    repositoryName: rmja/Cloudspool
    assets: $(Build.ArtifactStagingDirectory)/*
    action: edit
    target: '$(Build.SourceVersion)'
    tag: $(githubTag)
    addChangeLog: true
    assetUploadMode: replace