# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  Version.MajorMinor: 1.0
  Version.Patch: $[counter(variables['Version.MajorMinor'], 0)]

name: $(Build.DefinitionName)-$(Version.MajorMinor).$(Version.Patch)

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    versioningScheme: byBuildNumber