trigger: none

pool:
  vmImage: 'ubuntu-latest'

# See https://github.com/microsoft/azure-pipelines-tasks/issues/11558 for creating the "github" service connection
# 1. Create a personal access token for Azure DevOps to create the service connection. Do this from https://dev.azure.com/rmja/_usersSettings/tokens
# 2. Create a personal access token for Github. Do this from https://github.com/settings/tokens
#    The recommended scopes are: repo, user, admin:repo_hook (see https://dev.azure.com/rmja/Cloudspool/_settings/adminservices)
# AZURE_PAL = "Token obtained from Azure DevOps"
# GITHUB_PAL = "Token obtained from Github"
# 3. Run the following curl command from bash:
# curl -u rmja:AZURE_PAL \
#    -d '{"name": "github-release","type": "github","url": "https://github.com","authorization":{"scheme":"PersonalAccessToken","parameters":{"accessToken":"GITHUB_PAL"}}}' \
#    -H "Content-Type: application/json" \
#    -X POST \
#    'https://dev.azure.com/rmja/Cloudspool/_apis/serviceendpoint/endpoints?api-version=5.1-preview'
steps:
- task: GithubRelease@0
  displayName: 'Create GitHub release draft'
  inputs:
    gitHubConnection: github-release
    repositoryName: rmja/Cloudspool
    action: create
    assets: $(Build.ArtifactStagingDirectory)/*
    target: '$(Build.SourceVersion)'
    addChangeLog: true
    isDraft: true