trigger:
  branches:
    include:
    - master
    - releases/*
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

# See https://github.com/microsoft/azure-pipelines-tasks/issues/11558#issuecomment-541635061 for creating the "github" service connection
# The curl command is in create-github-service-connection.cmd
steps:
- task: GithubRelease@0
  displayName: 'Attach artifact assets to GitHub Release'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  inputs:
    gitHubConnection: github
    repositoryName: rmja/Cloudspool
    assets: $(Build.ArtifactStagingDirectory)/*
    action: edit
    target: '$(Build.SourceVersion)'
    tag: $(githubTag)
    addChangeLog: true
    assetUploadMode: replace